-- MySQL Script generated by MySQL Workbench
-- Mon Mar  1 21:15:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `DOB` DATE NOT NULL,
  `PhoneNumber` VARCHAR(15) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `Zip` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `AccountCreationDate` DATE NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `SecurityQuestion1` TINYTEXT NOT NULL,
  `Answer1` VARCHAR(45) NOT NULL,
  `SecurityQuestion2` TINYTEXT NOT NULL,
  `Answer2` VARCHAR(45) NOT NULL,
  `SecurityQuestion3` TINYTEXT NOT NULL,
  `Answer3` VARCHAR(45) NOT NULL,
  `Recently Played` VARCHAR(45) NULL,
  `Recent Play Time` TIMESTAMP NULL,
  `Last Played Date` DATE NULL,
  `Total Time Played` TIMESTAMP NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `UserName_UNIQUE` ON `mydb`.`User` (`UserName` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Games` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Games` (
  `GameID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `Description` TEXT(1000) NULL,
  `Multiplayer` TINYINT NULL,
  `ESRB_Rating` VARCHAR(4) NULL,
  `Gamescol` VARCHAR(45) NULL,
  `DateReleased` DATE NULL,
  `Publisher` VARCHAR(45) NULL,
  `Developer` VARCHAR(45) NULL,
  `Notes` TINYTEXT NULL,
  `CommunityReview` DECIMAL(2,1) NULL,
  `IGNReview` DECIMAL(2,1) NULL,
  `Platform` VARCHAR(45) NULL,
  PRIMARY KEY (`GameID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserGame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UserGame` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UserGame` (
  `UserID` INT NOT NULL,
  `GameID` INT NOT NULL,
  `UserIGN` DECIMAL(2,1) NULL,
  `UserReview` TEXT(1000) NULL,
  `UserRating` DECIMAL(2,1) NULL,
  `LastTimePlayed` DATE NULL,
  `Notes` TEXT(1000) NULL,
  `UserGamecol` VARCHAR(45) NULL,
  `TotalTimePlayed` TIMESTAMP(6) NULL,
  `User_UserID` INT NOT NULL,
  `Games_GameID` INT NOT NULL,
  PRIMARY KEY (`UserID`, `GameID`, `User_UserID`, `Games_GameID`),
  CONSTRAINT `fk_UserGame_User`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `mydb`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserGame_Games1`
    FOREIGN KEY (`Games_GameID`)
    REFERENCES `mydb`.`Games` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_UserGame_User_idx` ON `mydb`.`UserGame` (`User_UserID` ASC) VISIBLE;

CREATE INDEX `fk_UserGame_Games1_idx` ON `mydb`.`UserGame` (`Games_GameID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tags` (
  `Tags` INT NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Tags`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GameTags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GameTags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GameTags` (
  `GameID` INT NOT NULL,
  `TagID` VARCHAR(45) NOT NULL,
  `Games_GameID` INT NOT NULL,
  `Tags_Tags` INT NOT NULL,
  PRIMARY KEY (`GameID`, `TagID`, `Games_GameID`, `Tags_Tags`),
  CONSTRAINT `fk_GameTags_Games1`
    FOREIGN KEY (`Games_GameID`)
    REFERENCES `mydb`.`Games` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GameTags_Tags1`
    FOREIGN KEY (`Tags_Tags`)
    REFERENCES `mydb`.`Tags` (`Tags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_GameTags_Games1_idx` ON `mydb`.`GameTags` (`Games_GameID` ASC) VISIBLE;

CREATE INDEX `fk_GameTags_Tags1_idx` ON `mydb`.`GameTags` (`Tags_Tags` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`GameAchievements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GameAchievements` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GameAchievements` (
  `GameID` INT NOT NULL,
  `AchievementId` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Games_GameID` INT NOT NULL,
  PRIMARY KEY (`AchievementId`, `GameID`, `Games_GameID`),
  CONSTRAINT `fk_GameAchievements_Games1`
    FOREIGN KEY (`Games_GameID`)
    REFERENCES `mydb`.`Games` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_GameAchievements_Games1_idx` ON `mydb`.`GameAchievements` (`Games_GameID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`UserAchievement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UserAchievement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UserAchievement` (
  `UserID` INT NOT NULL,
  `GameID` INT NOT NULL,
  `AchievementID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Completed` TINYINT NOT NULL,
  `Date Completed` DATE NULL,
  `UserGame_UserID` INT NOT NULL,
  `UserGame_GameID` INT NOT NULL,
  `UserGame_User_UserID` INT NOT NULL,
  `UserGame_Games_GameID` INT NOT NULL,
  `GameAchievements_AchievementId` VARCHAR(45) NOT NULL,
  `GameAchievements_GameID` INT NOT NULL,
  `GameAchievements_Games_GameID` INT NOT NULL,
  PRIMARY KEY (`UserID`, `GameID`, `AchievementID`, `UserGame_UserID`, `UserGame_GameID`, `UserGame_User_UserID`, `UserGame_Games_GameID`, `GameAchievements_AchievementId`, `GameAchievements_GameID`, `GameAchievements_Games_GameID`),
  CONSTRAINT `fk_UserAchievement_UserGame1`
    FOREIGN KEY (`UserGame_UserID` , `UserGame_GameID` , `UserGame_User_UserID` , `UserGame_Games_GameID`)
    REFERENCES `mydb`.`UserGame` (`UserID` , `GameID` , `User_UserID` , `Games_GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserAchievement_GameAchievements1`
    FOREIGN KEY (`GameAchievements_AchievementId` , `GameAchievements_GameID` , `GameAchievements_Games_GameID`)
    REFERENCES `mydb`.`GameAchievements` (`AchievementId` , `GameID` , `Games_GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_UserAchievement_UserGame1_idx` ON `mydb`.`UserAchievement` (`UserGame_UserID` ASC, `UserGame_GameID` ASC, `UserGame_User_UserID` ASC, `UserGame_Games_GameID` ASC) VISIBLE;

CREATE INDEX `fk_UserAchievement_GameAchievements1_idx` ON `mydb`.`UserAchievement` (`GameAchievements_AchievementId` ASC, `GameAchievements_GameID` ASC, `GameAchievements_Games_GameID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
